### ISSUE TITLE
Pre-Beta Checklist

### ISSUE THREAD

**Issue by ralphbean** [ralphbean/pep8bot#6]
Stuff to do before an announcement.
- [x] first, on web198, fix the worker to handle the pull request..
- [x] see https://api.github.com/repos/ralphbean/cruciverbalist/commits/7b1812aceb80970e08340ea6b6db2b2365cfbfed
- [x] merge from web198 and here
- [ ] move the gh_users stuff out of the Profile widget into the model
- [ ] add a "sync" button to refresh model from gh
- [ ] begin including organization repos
- [ ] add button columns for pyflakes and mccabe
- [ ] remove widget tab from UI
- [ ] test against fedora-infra in pre-beta mode.
